// <auto-generated />
namespace CURDUsingJquery.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FirstMigratio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstMigratio));
        
        string IMigrationMetadata.Id
        {
            get { return "201906251358301_FirstMigratio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
